import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'RIFTTRACKER',
  description: 'Generated by shys',
}

export default async function RootLayout({ children }) {
  return (
    <html>
      <body>
      <h1><Link href="/">RIFTTRACKER</Link></h1>
      <ol>
        <li><Link href="/liotaccount">전적검색</Link></li>
      </ol>
        {children}
      </body>
    </html>
  )
}